### ISSUE TITLE
XPathResult.prototype.iterateNext has a mistake

### ISSUE THREAD

**Issue by odedsh** [badeball/xpath-evaluator#1]
Current IterateNext will always return the first node

The culprit is this line which has two mistakes.

return (this.index.length >= this.nodes.length) ? null : this.nodes[this.index];

1) The condition is wrong
2) Noone is incrementing the index

It should look like this:

return (this.index >= this.nodes.length) ? null : this.nodes[this.index++];

**Comment by badeball** [comment]
Hi, @odedsh! Thanks for reporting this issue. I've corrected it with 99c0f85 and released it in version 2.0.1.
